// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"github.com/T-Graduation-Project/borrow-server/app/model/internal"
)

// BookInfo is the golang structure for table book_info.
type BookInfo internal.BookInfo

// Fill with you ideas below.
