// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"github.com/T-Graduation-Project/borrow-server/app/model/internal"
)

// BorrowList is the golang structure for table borrow_list.
type BorrowList internal.BorrowList

// Fill with you ideas below.
