// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"github.com/T-Graduation-Project/borrow-server/app/model/internal"
)

// UserInfo is the golang structure for table user_info.
type UserInfo internal.UserInfo

// Fill with you ideas below.
