// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// BookInfo is the golang structure for table book_info.
type BookInfo struct {
	Id           int         `orm:"id,primary"   json:"id"`           //
	Name         string      `orm:"name"         json:"name"`         // 书名
	Author       string      `orm:"author"       json:"author"`       // 作者
	Publish      string      `orm:"publish"      json:"publish"`      // 出版社
	Introduction string      `orm:"introduction" json:"introduction"` // 简介
	Number       int         `orm:"number"       json:"number"`       // 剩余数量
	ISBN         string      `orm:"ISBN"         json:"iSBN"`         // 标准书号
	UpdateTime   *gtime.Time `orm:"update_time"  json:"updateTime"`   //
	CreateTime   *gtime.Time `orm:"create_time"  json:"createTime"`   //
}
