// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// UserInfo is the golang structure for table user_info.
type UserInfo struct {
	Id       int    `orm:"id,primary" json:"id"`       //
	Username string `orm:"username"   json:"username"` // 用户账号
	Password string `orm:"password"   json:"password"` // 用户密码
}
