// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol/borrow.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Book struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Author               string   `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Publish              string   `protobuf:"bytes,4,opt,name=publish,proto3" json:"publish,omitempty"`
	Introduction         string   `protobuf:"bytes,5,opt,name=introduction,proto3" json:"introduction,omitempty"`
	Number               int64    `protobuf:"varint,6,opt,name=number,proto3" json:"number,omitempty"`
	ISBN                 string   `protobuf:"bytes,7,opt,name=ISBN,proto3" json:"ISBN,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_a706cddf1f5749cb, []int{0}
}

func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (m *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(m, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Book) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Book) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Book) GetPublish() string {
	if m != nil {
		return m.Publish
	}
	return ""
}

func (m *Book) GetIntroduction() string {
	if m != nil {
		return m.Introduction
	}
	return ""
}

func (m *Book) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Book) GetISBN() string {
	if m != nil {
		return m.ISBN
	}
	return ""
}

type BorrowBookReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BookId               int64    `protobuf:"varint,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BorrowBookReq) Reset()         { *m = BorrowBookReq{} }
func (m *BorrowBookReq) String() string { return proto.CompactTextString(m) }
func (*BorrowBookReq) ProtoMessage()    {}
func (*BorrowBookReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a706cddf1f5749cb, []int{1}
}

func (m *BorrowBookReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BorrowBookReq.Unmarshal(m, b)
}
func (m *BorrowBookReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BorrowBookReq.Marshal(b, m, deterministic)
}
func (m *BorrowBookReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BorrowBookReq.Merge(m, src)
}
func (m *BorrowBookReq) XXX_Size() int {
	return xxx_messageInfo_BorrowBookReq.Size(m)
}
func (m *BorrowBookReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BorrowBookReq.DiscardUnknown(m)
}

var xxx_messageInfo_BorrowBookReq proto.InternalMessageInfo

func (m *BorrowBookReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *BorrowBookReq) GetBookId() int64 {
	if m != nil {
		return m.BookId
	}
	return 0
}

type BorrowBookRsp struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BorrowBookRsp) Reset()         { *m = BorrowBookRsp{} }
func (m *BorrowBookRsp) String() string { return proto.CompactTextString(m) }
func (*BorrowBookRsp) ProtoMessage()    {}
func (*BorrowBookRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a706cddf1f5749cb, []int{2}
}

func (m *BorrowBookRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BorrowBookRsp.Unmarshal(m, b)
}
func (m *BorrowBookRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BorrowBookRsp.Marshal(b, m, deterministic)
}
func (m *BorrowBookRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BorrowBookRsp.Merge(m, src)
}
func (m *BorrowBookRsp) XXX_Size() int {
	return xxx_messageInfo_BorrowBookRsp.Size(m)
}
func (m *BorrowBookRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_BorrowBookRsp.DiscardUnknown(m)
}

var xxx_messageInfo_BorrowBookRsp proto.InternalMessageInfo

func (m *BorrowBookRsp) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *BorrowBookRsp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type ReturnBookReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BookId               int64    `protobuf:"varint,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	BorrowDate           string   `protobuf:"bytes,3,opt,name=borrow_date,json=borrowDate,proto3" json:"borrow_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReturnBookReq) Reset()         { *m = ReturnBookReq{} }
func (m *ReturnBookReq) String() string { return proto.CompactTextString(m) }
func (*ReturnBookReq) ProtoMessage()    {}
func (*ReturnBookReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a706cddf1f5749cb, []int{3}
}

func (m *ReturnBookReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReturnBookReq.Unmarshal(m, b)
}
func (m *ReturnBookReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReturnBookReq.Marshal(b, m, deterministic)
}
func (m *ReturnBookReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReturnBookReq.Merge(m, src)
}
func (m *ReturnBookReq) XXX_Size() int {
	return xxx_messageInfo_ReturnBookReq.Size(m)
}
func (m *ReturnBookReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReturnBookReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReturnBookReq proto.InternalMessageInfo

func (m *ReturnBookReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ReturnBookReq) GetBookId() int64 {
	if m != nil {
		return m.BookId
	}
	return 0
}

func (m *ReturnBookReq) GetBorrowDate() string {
	if m != nil {
		return m.BorrowDate
	}
	return ""
}

type ReturnBookRsp struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReturnBookRsp) Reset()         { *m = ReturnBookRsp{} }
func (m *ReturnBookRsp) String() string { return proto.CompactTextString(m) }
func (*ReturnBookRsp) ProtoMessage()    {}
func (*ReturnBookRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a706cddf1f5749cb, []int{4}
}

func (m *ReturnBookRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReturnBookRsp.Unmarshal(m, b)
}
func (m *ReturnBookRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReturnBookRsp.Marshal(b, m, deterministic)
}
func (m *ReturnBookRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReturnBookRsp.Merge(m, src)
}
func (m *ReturnBookRsp) XXX_Size() int {
	return xxx_messageInfo_ReturnBookRsp.Size(m)
}
func (m *ReturnBookRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ReturnBookRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ReturnBookRsp proto.InternalMessageInfo

func (m *ReturnBookRsp) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ReturnBookRsp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type DeleteRecordReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRecordReq) Reset()         { *m = DeleteRecordReq{} }
func (m *DeleteRecordReq) String() string { return proto.CompactTextString(m) }
func (*DeleteRecordReq) ProtoMessage()    {}
func (*DeleteRecordReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a706cddf1f5749cb, []int{5}
}

func (m *DeleteRecordReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRecordReq.Unmarshal(m, b)
}
func (m *DeleteRecordReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRecordReq.Marshal(b, m, deterministic)
}
func (m *DeleteRecordReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRecordReq.Merge(m, src)
}
func (m *DeleteRecordReq) XXX_Size() int {
	return xxx_messageInfo_DeleteRecordReq.Size(m)
}
func (m *DeleteRecordReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRecordReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRecordReq proto.InternalMessageInfo

func (m *DeleteRecordReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteRecordRsp struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRecordRsp) Reset()         { *m = DeleteRecordRsp{} }
func (m *DeleteRecordRsp) String() string { return proto.CompactTextString(m) }
func (*DeleteRecordRsp) ProtoMessage()    {}
func (*DeleteRecordRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a706cddf1f5749cb, []int{6}
}

func (m *DeleteRecordRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRecordRsp.Unmarshal(m, b)
}
func (m *DeleteRecordRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRecordRsp.Marshal(b, m, deterministic)
}
func (m *DeleteRecordRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRecordRsp.Merge(m, src)
}
func (m *DeleteRecordRsp) XXX_Size() int {
	return xxx_messageInfo_DeleteRecordRsp.Size(m)
}
func (m *DeleteRecordRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRecordRsp.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRecordRsp proto.InternalMessageInfo

func (m *DeleteRecordRsp) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DeleteRecordRsp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*Book)(nil), "borrow.Book")
	proto.RegisterType((*BorrowBookReq)(nil), "borrow.BorrowBookReq")
	proto.RegisterType((*BorrowBookRsp)(nil), "borrow.BorrowBookRsp")
	proto.RegisterType((*ReturnBookReq)(nil), "borrow.ReturnBookReq")
	proto.RegisterType((*ReturnBookRsp)(nil), "borrow.ReturnBookRsp")
	proto.RegisterType((*DeleteRecordReq)(nil), "borrow.DeleteRecordReq")
	proto.RegisterType((*DeleteRecordRsp)(nil), "borrow.DeleteRecordRsp")
}

func init() { proto.RegisterFile("protocol/borrow.proto", fileDescriptor_a706cddf1f5749cb) }

var fileDescriptor_a706cddf1f5749cb = []byte{
	// 352 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0xc1, 0x6e, 0xe2, 0x30,
	0x10, 0xdd, 0x04, 0x36, 0x68, 0x67, 0x61, 0xb7, 0x1a, 0x89, 0x62, 0x71, 0x29, 0xf5, 0x89, 0x13,
	0x95, 0x5a, 0x55, 0xbd, 0xf4, 0xd2, 0x88, 0x0b, 0x97, 0x1e, 0xd2, 0x0f, 0x40, 0x49, 0x6c, 0x95,
	0x08, 0xc8, 0xa4, 0x8e, 0xa3, 0xfe, 0x54, 0x3f, 0xa4, 0x9f, 0x55, 0x8d, 0x13, 0x0a, 0x41, 0x1c,
	0x50, 0x6f, 0xf3, 0xde, 0xf3, 0xcc, 0x3c, 0x3f, 0x1b, 0x86, 0x85, 0x21, 0x4b, 0x29, 0x6d, 0x6e,
	0x12, 0x32, 0x86, 0xde, 0x67, 0x0e, 0x63, 0x50, 0x23, 0xf9, 0xe1, 0x41, 0x37, 0x24, 0x5a, 0xe3,
	0x3f, 0xf0, 0x33, 0x25, 0xbc, 0x89, 0x37, 0xed, 0x44, 0x7e, 0xa6, 0x10, 0xa1, 0x9b, 0xc7, 0x5b,
	0x2d, 0xfc, 0x89, 0x37, 0xfd, 0x13, 0xb9, 0x1a, 0x2f, 0x21, 0x88, 0x2b, 0xbb, 0x22, 0x23, 0x3a,
	0x8e, 0x6d, 0x10, 0x0a, 0xe8, 0x15, 0x55, 0xb2, 0xc9, 0xca, 0x95, 0xe8, 0x3a, 0x61, 0x07, 0x51,
	0x42, 0x3f, 0xcb, 0xad, 0x21, 0x55, 0xa5, 0x36, 0xa3, 0x5c, 0xfc, 0x76, 0x72, 0x8b, 0xe3, 0xa9,
	0x79, 0xb5, 0x4d, 0xb4, 0x11, 0x81, 0xdb, 0xde, 0x20, 0x76, 0xb0, 0x78, 0x09, 0x9f, 0x45, 0xaf,
	0x76, 0xc0, 0xb5, 0x7c, 0x82, 0x41, 0xe8, 0x8c, 0xb3, 0xe7, 0x48, 0xbf, 0xe1, 0x08, 0x7a, 0x55,
	0xa9, 0xcd, 0xf2, 0xdb, 0x7b, 0xc0, 0x70, 0xa1, 0x58, 0x48, 0x88, 0xd6, 0x2c, 0xf8, 0xb5, 0xc0,
	0x70, 0xa1, 0xe4, 0x7d, 0x6b, 0x44, 0x59, 0xf0, 0x9e, 0x94, 0x94, 0x6e, 0xfa, 0x5d, 0x8d, 0x17,
	0xd0, 0xd9, 0x96, 0xaf, 0xcd, 0xe5, 0xb9, 0x94, 0x09, 0x0c, 0x22, 0x6d, 0x2b, 0x93, 0xff, 0x78,
	0x33, 0x5e, 0xc1, 0xdf, 0x3a, 0xf5, 0xa5, 0x8a, 0xad, 0x6e, 0x32, 0x84, 0x9a, 0x9a, 0xc7, 0x56,
	0xb3, 0xb5, 0x83, 0x1d, 0x67, 0x5b, 0xbb, 0x86, 0xff, 0x73, 0xbd, 0xd1, 0x56, 0x47, 0x3a, 0x25,
	0xa3, 0xd8, 0xdc, 0xd1, 0x6b, 0xca, 0x87, 0xa3, 0x23, 0xe7, 0xce, 0xbe, 0xfd, 0xf4, 0x20, 0xa8,
	0xe3, 0xc2, 0x47, 0x80, 0x7d, 0x70, 0x38, 0x9c, 0x35, 0xff, 0xa9, 0xf5, 0x1e, 0xe3, 0x53, 0x74,
	0x59, 0xc8, 0x5f, 0xdc, 0xbd, 0xbf, 0xdb, 0xbe, 0xbb, 0x95, 0xe9, 0xf8, 0x14, 0xed, 0xba, 0x43,
	0xe8, 0x1f, 0xfa, 0xc7, 0xd1, 0xee, 0xe0, 0xd1, 0xc5, 0xc7, 0xa7, 0x05, 0x9e, 0x91, 0x04, 0xee,
	0xe7, 0xdf, 0x7d, 0x05, 0x00, 0x00, 0xff, 0xff, 0x7b, 0x96, 0x12, 0x50, 0x12, 0x03, 0x00, 0x00,
}
