# 注册发现
[discovery]
    endpoints = ["127.0.0.1:2379"]

# GRPC Server
[grpcserver]
    appId            = "borrow"
	address          = ":58080"
    accessLogEnabled = true

# Logger configurations.
[logger]
    Path   = "/tmp/log/server"
    Level  = "all"
    Stdout = true

[database]
    [[database.default]]
        link  = "mysql:root:123456@tcp(159.75.125.159:3307)/library"
        role  = "master"
        debug = true

    # 数据库日志对象配置
    [database.logger]
        Path   = "/tmp/log/sql"
        Level  = "all"
        Stdout = true

# GF-CLI工具配置
[gfcli]
    # 自定义DAO生成配置(默认是读取database配置)
    [[gfcli.gen.dao]]
        link   = "mysql:root:123456@tcp(9.135.9.19:3306)/library"
        tables = "book_info"
    [[gfcli.gen.dao]]
        link  = "mysql:root:123456@tcp(9.135.9.19:3306)/library"
        tables = "user_info"
    [[gfcli.gen.dao]]
        link  = "mysql:root:123456@tcp(9.135.9.19:3306)/library"
        tables = "borrow_list"