// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"github.com/T-Graduation-Project/borrow-server/app/dao/internal"
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
)

// bookInfoDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type bookInfoDao struct {
	*internal.BookInfoDao
}

var (
	// BookInfo is globally public accessible object for table book_info operations.
	BookInfo = &bookInfoDao{
		internal.BookInfo,
	}
)

// Fill with you ideas below.
func SelectBook(dbEnv string, namespace string) gdb.Result {
	db := g.DB(dbEnv)
	r := new(gdb.Result)
	if namespace == "" {
		*r, _ = db.Table("book_info").All()
	} else {
		// TODO
		*r, _ = db.Table(
			"cmd_info ci,proto_file_info pfi").Where(
			"pfi.namespace", namespace).Where(
			"ci.file_id=pfi.file_id").Fields(
			"ci.cmd,pfi.filename,pfi.namespace").All()
	}
	return *r
}

func SaveBorrowList(dbEnv string, p g.Map) error {
	db := g.DB(dbEnv)
	_, err := db.Table("borrow_list").Save(p)
	if err != nil {
		return err
	}
	return nil
}
