// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"github.com/T-Graduation-Project/borrow-server/app/dao/internal"
)

// borrowListDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type borrowListDao struct {
	*internal.BorrowListDao
}

var (
	// BorrowList is globally public accessible object for table borrow_list operations.
	BorrowList = &borrowListDao{
		internal.BorrowList,
	}
)

// Fill with you ideas below.
